---
apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME
  namespace: K8S_NAMESPACE
  labels:
    app: APP_LABEL
spec:
  containers:
    - name: CONTAINER_NAME
      image: SOURCE_IMAGE
      ports:
        - containerPort: CONTAINER_PORT

